export const AUDIT = {
  // ADMIN
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
  ADMIN_LOGOUT_ALL: "ADMIN_LOGOUT_ALL",

  // STORE
  STORE_REGISTER: "STORE_REGISTER",
  STORE_LOGIN_SUCCESS: "STORE_LOGIN_SUCCESS",
  STORE_LOGIN_FAIL: "STORE_LOGIN_FAIL",
  STORE_LOGOUT: "STORE_LOGOUT",
  STORE_LOGOUT_ALL: "STORE_LOGOUT_ALL",

  // COMMON (ama meta.typ ile ayıracağız)
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_CONFIRM: "PASSWORD_RESET_CONFIRM",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",

  SESSION_REFRESH: "SESSION_REFRESH",
  SESSION_REUSE_DETECTED: "SESSION_REUSE_DETECTED",
  SESSION_REVOKE_GLOBAL: "SESSION_REVOKE_GLOBAL",
  // RL
  PASSWORD_RESET_REQUEST_RATE_LIMITED: "PASSWORD_RESET_REQUEST_RATE_LIMITED",
  PASSWORD_RESET_CONFIRM_RATE_LIMITED: "PASSWORD_RESET_CONFIRM_RATE_LIMITED",
  STORE_LOGIN_RATE_LIMITED: "STORE_LOGIN_RATE_LIMITED",
  STORE_REGISTER_RATE_LIMITED: "STORE_REGISTER_RATE_LIMITED",
  ADMIN_LOGIN_RATE_LIMITED: "ADMIN_LOGIN_RATE_LIMITED",
} as const;
