import type { Metadata } from 'next'
import '@/assets/scss/style.scss'
import AppProvidersWrapper from '@/components/wrapper/AppProvidersWrapper'
import { DEFAULT_PAGE_TITLE } from '@/context/constants'
import { TenantProvider } from '@/lib/tenant-context'

import { Roboto } from 'next/font/google'

const roboto = Roboto({
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})
export const metadata: Metadata = {
  title: {
    template: '%s | Ecom - E-commerce Platform',
    default: DEFAULT_PAGE_TITLE,
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={roboto.className}>
        <div id="__next_splash">
          <AppProvidersWrapper>
            <TenantProvider>{children}</TenantProvider>
          </AppProvidersWrapper>


        </div>
      </body>
    </html>
  )
}
