// src/infrastructure/errors/error-codes.ts

export const ERROR_CODES = {
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  TENANT_CONTEXT_MISSING: "TENANT_CONTEXT_MISSING",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PRISMA_ERROR: "PRISMA_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
