#ecom-infra/docker/compose.api.dev.yml

services:
  api:
    image: node:20-bookworm-slim
    container_name: ecom_api
    working_dir: /app

    restart: unless-stopped
    init: true

    env_file:
      - ../.env

    environment:
      NODE_ENV: development
      API_PORT: ${API_PORT:-3001}
      CI: "true"

      DATABASE_URL: ${DATABASE_URL}

      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}

      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://ecom_minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
      MINIO_BUCKET: ${MINIO_BUCKET:-ecom}
      MINIO_REGION: ${MINIO_REGION:-us-east-1}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      TENANT_CONFIG_PATH: /app/src/config/tenant.json


      # ts-node / tools için (seed vb.)
      TS_NODE_PROJECT: "tsconfig.json"
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: ${MINIO_BUCKET:-ecom}
      S3_REGION: us-east-1
      S3_FORCE_PATH_STYLE: "true"
      S3_ENDPOINT_INTERNAL: "http://minio:9000"
      S3_ENDPOINT_PUBLIC: "http://localhost:9000"



      # AWS SDK credential (kritik)
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER:-minio}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD:-minio_password_123}
      AWS_REGION: us-east-1

      # ❗️ÖNEMLİ: NODE_OPTIONS burada YOK.
      # Çünkü preload (tsconfig-paths/register) pnpm install'dan önce çalışırsa container exit 0 döngüsüne girer.

    ports:
      - "${API_PORT:-3001}:3001"

    volumes:
      - ${API_REPO_PATH:?set API_REPO_PATH to your ecom-api path}:/app
      - /app/node_modules
      
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"fetch('http://localhost:3001/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 40s

    command: >
      sh -lc "
        set -eu
        cd /app
        apt-get update -y &&
        apt-get install -y --no-install-recommends openssl libssl3 ca-certificates procps &&
        rm -rf /var/lib/apt/lists/* &&
    
        corepack enable
        corepack prepare pnpm@10.26.1 --activate
    
        pnpm install
        pnpm prisma:generate
    
        echo 'Starting Nest...'
        exec node -r tsconfig-paths/register ./node_modules/@nestjs/cli/bin/nest.js start --watch
      "

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

    networks:
      - ecom_net

networks:
  ecom_net:
    external: true
    name: ecom_net
