name: ecom_suite

services:
  prisma_migrate:
    image: node:20-bookworm-slim
    working_dir: /work
    env_file: ../.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PRISMA_VERSION: ${PRISMA_VERSION:-7.2.0}
    volumes:
      - ../prisma:/work/prisma:ro
      - ../prisma:/work/prisma
    entrypoint: ["sh", "-lc"]
    command: >
      npx -y prisma@${PRISMA_VERSION} migrate deploy
      --schema /work/prisma/schema.prisma

  prisma_studio:
    image: node:20-alpine
    container_name: ecom_prisma_studio
    working_dir: /workspace
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PRISMA_STUDIO_PORT:-5555}:5555"
    volumes:
      - ../../../ecom-api:/workspace/ecom-api
    entrypoint: ["sh", "-lc"]
    command: >
      npm -g i prisma@${PRISMA_VERSION:-7.2.0} &&
      prisma studio --schema /workspace/ecom-api/prisma/schema.prisma --port 5555 --hostname 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
